### PR TITLE
Add Internet Explorer polyfills

### PR DESCRIPTION
**Pull request by piboistudios**
IE9+ Compatibility

### CODE REVIEW

**Comment by nikolasp** [comment]
Hi @piboistudios,

Thanks for the pull request. 
I don't think that we should pack polyfills with the library. It's always better to do that on application level, especially today when almost everything is bundled (webpack, parcel, rollup, etc). 
However, maybe we can pack polyfills but say to users that they will have to import additional js file if they want to support IE and that will be stated in README. What do you think about this?

I share the same thoughts as @sokra when it comes to polyfills.
Take a look at https://github.com/w3ctag/polyfills/issues/6#issuecomment-272647475

**Comment by piboistudios** [comment]
That's a good point.

Maybe include it as a part of the README.md in an added Browser Compatibility section?

**Comment by nikolasp** [comment]
Sure, I'll do that. I think that we can accept your pull request, just before that we need to remove 
`import './polyfills';` from `src/index.js` and then in README we can point out this file for IE support.

**Comment by nikolasp** [comment]
Thanks @piboistudios, 🎉 

I'll add you to the list of contributors.

**Pull request merged**
